language: node_js
node_js:
  - 10

#指定分支，只有指定分支的提交才会运行脚本
branches:
  only:
    - dev

cache:
  directories:
    - node_modules

install:
  - yarn install

#项目执行命令  
script:
   # 执行测试的命令
  - yarn cover
